name: healer
author: SuperBaronDEV
api: [3.0.0]
version: 1.0.0
main: SuperBaronDEV\healer\healer
commands:
  heal:
    description: heal the player!
    usage: /heal
  permissions: heal.use
  deafult: op
